const {model, Schema, SchemaTypes,connect, disconnect} = require('mongoose');

const schema = new Schema({
  variant_id: { type: SchemaTypes.String, required: true, unique: true },
  variant_name: { type: SchemaTypes.String, required: true },
  description: { type: SchemaTypes.String, required: true },
  slug: { type: SchemaTypes.String, required: true, unique: true },
  car_id: { type: SchemaTypes.String, required: true },
  exshowroom_price: { type: SchemaTypes.String, required: true },
  engine_and_transmission: {
    engine_type: { type: String, default: 'N/A' },
    displacement: { type: String, default: 'N/A' },
    max_power: { type: String, default: 'N/A' },
    max_torque: { type: String, default: 'N/A' },
    number_of_cylinders: { type: String, default: 'N/A' },
    valves_per_cylinder: { type: String, default: 'N/A' },
    valve_configuration: { type: String, default: 'N/A' },
    fuel_supply_system: { type: String, default: 'N/A' },
    turbo_charger: { type: Boolean, default: false },
    transmission_type: { type: String, default: 'N/A' },
    gearbox: { type: String, default: 'N/A' },
    drive_type: { type: String, default: 'N/A' },
    hybrid_type: { type: String, default: 'N/A' },
    super_charge: { type: Boolean, default: false },
    regenerative_braking: { type: Boolean, default: false },
  },
  fuel_and_performance: {
    fuel_type: { type: String, default: 'N/A' },
    mileage_arai: { type: String, default: 'N/A' },
    fuel_tank_capacity: { type: String, default: 'N/A' },
    emission_norm_compliance: { type: String, default: 'N/A' },
    top_speed: { type: String, default: 'N/A' },
    secondary_fuel_type: { type: String, default: 'N/A' },
    highway_mileage: { type: String, default: 'N/A' },
  },
  suspension_steering_and_brakes: {
    front_suspension: { type: String, default: 'N/A' },
    rear_suspension: { type: String, default: 'N/A' },
    steering_type: { type: String, default: 'N/A' },
    steering_column: { type: String, default: 'N/A' },
    turning_radius: { type: String, default: 'N/A' },
    front_brake_type: { type: String, default: 'N/A' },
    rear_brake_type: { type: String, default: 'N/A' },
    alloy_wheel_size_front: { type: String, default: 'N/A' },
    alloy_wheel_size_rear: { type: String, default: 'N/A' },
    acceleration: { type: String, default: 'N/A' },
    zero_to_hundred_kmph: { type: String, default: 'N/A' },
  },
  dimensions_and_capacity: {
    length: { type: String, default: 'N/A' },
    width: { type: String, default: 'N/A' },
    height: { type: String, default: 'N/A' },
    boot_space: { type: String, default: 'N/A' },
    gross_weight: { type: String, default: 'N/A' },
    kerb_weight: { type: String, default: 'N/A' },
    seating_capacity: { type: String, default: 'N/A' },
    ground_clearance_unladen: { type: String, default: 'N/A' },
    wheel_base: { type: String, default: 'N/A' },
    number_of_doors: { type: String, default: 'N/A' },
    reported_boot_space: { type: String, default: 'N/A' },
  },
  comfort_and_convenience: {
    power_steering: { type: Boolean, default: false },
    air_conditioner: { type: Boolean, default: false },
    heater: { type: Boolean, default: false },
    adjustable_steering: { type: Boolean, default: false },
    height_adjustable_driver_seat: { type: Boolean, default: false },
    ventilated_seats: { type: Boolean, default: false },
    electric_adjustable_seats: { type: String, default: 'N/A' },
    automatic_climate_control: { type: Boolean, default: false },
    accessory_power_outlet: { type: Boolean, default: false },
    trunk_light: { type: Boolean, default: false },
    vanity_mirror: { type: Boolean, default: false },
    rear_reading_lamp: { type: Boolean, default: false },
    adjustable_headrest: { type: Boolean, default: false },
    rear_seat_centre_arm_rest: { type: Boolean, default: false },
    height_adjustable_front_seat_belts: { type: Boolean, default: false },
    rear_ac_vents: { type: Boolean, default: false },
    cruise_control: { type: Boolean, default: false },
    parking_sensors: { type: String, default: 'N/A' },
    foldable_rear_seat: { type: String, default: 'N/A' },
    keyless_entry: { type: Boolean, default: false },
    engine_start_stop_button: { type: Boolean, default: false },
    cooled_glovebox: { type: Boolean, default: false },
    voice_commands: { type: Boolean, default: false },
    paddle_shifters: { type: Boolean, default: false },
    usb_charger: { type: String, default: 'N/A' },
    central_console_armrest: { type: String, default: 'N/A' },
    hands_free_tailgate: { type: Boolean, default: false },
    drive_modes: { type: String, default: 'N/A' },
    idle_start_stop_system: { type: Boolean, default: false },
    rear_window_sunblind: { type: Boolean, default: false },
    automatic_headlamps: { type: Boolean, default: false },
    follow_me_home_headlamps: { type: Boolean, default: false },
    additional_features: { type: String, default: 'N/A' },
    voice_assisted_sunroof: { type: Boolean, default: false },
    drive_mode_types: { type: String, default: 'N/A' },
    power_windows: { type: String, default: 'N/A' },
    remote_trunk_opener: { type: Boolean, default: false },
    remote_fuel_lid_opener: { type: Boolean, default: false },
    low_fuel_warning_light: { type: Boolean, default: false },
    rear_seat_headrest: { type: Boolean, default: false },
    lumbar_support: { type: Boolean, default: false },
    navigation_system: { type: Boolean, default: false },
    smart_access_card_entry: { type: Boolean, default: false },
    key_less_entry: { type: Boolean, default: false },
    tailgate_ajar_warning: { type: Boolean, default: false },
    gear_shift_indicator: { type: Boolean, default: false },
    rear_curtain: { type: Boolean, default: false },
    luggage_hook_and_net: { type: Boolean, default: false },
    battery_saver: { type: Boolean, default: false },
    lane_change_indicator: { type: Boolean, default: false },
  },
  interior: {
    tachometer: { type: Boolean, default: false },
    glove_box: { type: Boolean, default: false },
    digital_odometer: { type: Boolean, default: false },
    dual_tone_dashboard: { type: Boolean, default: false },
    additional_features: { type: String, default: 'N/A' },
    digital_cluster: { type: String, default: 'N/A' },
    digital_cluster_size: { type: String, default: 'N/A' },
    upholstery: { type: String, default: 'N/A' },
    electronic_multi_tripmeter: { type: Boolean, default: false },
    leather_seats: { type: Boolean, default: false },
    leather_wrapped_steering_wheel: { type: Boolean, default: false },
    digital_clock: { type: Boolean, default: false },
    outside_temperature_display: { type: Boolean, default: false },
    cigarette_lighter: { type: Boolean, default: false },
    driving_experience_control_eco: { type: Boolean, default: false },
    folding_table_in_the_rear: { type: Boolean, default: false },
  },
  exterior: {
    adjustable_headlamps: { type: Boolean, default: false },
    rain_sensing_wiper: { type: Boolean, default: false },
    automatic_headlamps: { type: Boolean, default: false },
    orvm: { type: String, default: 'N/A' },
    led_fog_lamps: { type: Boolean, default: false },
    rear_window_wiper: { type: Boolean, default: false },
    rear_window_washer: { type: Boolean, default: false },
    rear_window_defogger: { type: Boolean, default: false },
    wheel_covers: { type: Boolean, default: false },
    alloy_wheels: { type: Boolean, default: false },
    rear_spoiler: { type: Boolean, default: false },
    outside_rear_view_mirror_turn_indicators: { type: Boolean, default: false },
    integrated_antenna: { type: Boolean, default: false },
    projector_headlamps: { type: Boolean, default: false },
    roof_rails: { type: Boolean, default: false },
    antenna: { type: String, default: 'N/A' },
    boot_opening: { type: String, default: 'N/A' },
    puddle_lamps: { type: Boolean, default: false },
    outside_rear_view_mirror: { type: String, default: 'N/A' },
    tyre_size: { type: String, default: 'N/A' },
    tyre_type: { type: String, default: 'N/A' },
    led_drls: { type: Boolean, default: false },
    led_headlamps: { type: Boolean, default: false },
    led_taillights: { type: Boolean, default: false },
    fog_lights_front: { type: Boolean, default: false },
    fog_lights_rear: { type: Boolean, default: false },
    power_antenna: { type: Boolean, default: false },
    tinted_glass: { type: Boolean, default: false },
    roof_carrier: { type: Boolean, default: false },
    side_stepper: { type: Boolean, default: false },
    chrome_grille: { type: Boolean, default: false },
    chrome_garnish: { type: Boolean, default: false },
    smoke_headlamps: { type: Boolean, default: false },
    trunk_opener: { type: String, default: 'N/A' },
    heated_wing_mirror: { type: Boolean, default: false },
    sun_roof: { type: String, default: 'N/A' },
    additional_features: { type: String, default: 'N/A' },
  },
  safety: {
    anti_lock_braking_system: { type: Boolean, default: false },
    central_locking: { type: Boolean, default: false },
    child_safety_locks: { type: Boolean, default: false },
    anti_theft_alarm: { type: Boolean, default: false },
    number_of_airbags: { type: String, default: 'N/A' },
    driver_airbag: { type: Boolean, default: false },
    passenger_airbag: { type: Boolean, default: false },
    side_airbag: { type: Boolean, default: false },
    side_airbag_rear: { type: Boolean, default: false },
    day_and_night_rear_view_mirror: { type: Boolean, default: false },
    curtain_airbag: { type: Boolean, default: false },
    electronic_brakeforce_distribution: { type: Boolean, default: false },
    seat_belt_warning: { type: Boolean, default: false },
    door_ajar_warning: { type: Boolean, default: false },
    traction_control: { type: Boolean, default: false },
    tyre_pressure_monitoring_system: { type: Boolean, default: false },
    engine_immobilizer: { type: Boolean, default: false },
    electronic_stability_control: { type: Boolean, default: false },
    rear_camera: { type: String, default: 'N/A' },
    anti_theft_device: { type: Boolean, default: false },
    anti_pinch_power_windows: { type: Boolean, default: false },
    speed_alert: { type: Boolean, default: false },
    speed_sensing_auto_door_lock: { type: Boolean, default: false },
    knee_airbags: { type: Boolean, default: false },
    isofix_child_seat_mounts: { type: Boolean, default: false },
    pretensioners_and_force_limiter_seatbelts: { type: String, default: 'N/A' },
    hill_assist: { type: Boolean, default: false },
    impact_sensing_auto_door_unlock: { type: Boolean, default: false },
    view_camera_360: { type: Boolean, default: false },
    brake_assist: { type: Boolean, default: false },
    xenon_headlamps: { type: Boolean, default: false },
    heads_up_display_hud: { type: Boolean, default: false },
    hill_descent_control: { type: Boolean, default: false },
    global_ncap_safety_rating: { type: String, default: 'N/A' },
  },
  entertainment_and_communication: {
    radio: { type: Boolean, default: false },
    integrated_2din_audio: { type: Boolean, default: false },
    wireless_phone_charging: { type: Boolean, default: false },
    bluetooth_connectivity: { type: Boolean, default: false },
    touchscreen: { type: Boolean, default: false },
    touchscreen_size: { type: String, default: 'N/A' },
    connectivity: { type: String, default: 'N/A' },
    android_auto: { type: Boolean, default: false },
    apple_car_play: { type: Boolean, default: false },
    number_of_speakers: { type: String, default: 'N/A' },
    usb_ports: { type: Boolean, default: false },
    inbuilt_apps: { type: String, default: 'N/A' },
    tweeters: { type: String, default: 'N/A' },
    subwoofer: { type: String, default: 'N/A' },
    additional_features: { type: String, default: 'N/A' },
    audio_system_remote_control: { type: Boolean, default: false },
    mirror_link: { type: Boolean, default: false },
    usb_and_auxiliary_input: { type: Boolean, default: false },
    wi_fi_connectivity: { type: Boolean, default: false },
    compass: { type: Boolean, default: false },
    speakers: { type: String, default: 'N/A' },
  },
  adas_feature: {
    forward_collision_warning: { type: Boolean, default: false },
    blind_spot_collision_avoidance_assist: { type: Boolean, default: false },
    lane_departure_warning: { type: Boolean, default: false },
    lane_keep_assist: { type: Boolean, default: false },
    driver_attention_warning: { type: Boolean, default: false },
    adaptive_cruise_control: { type: Boolean, default: false },
    leading_vehicle_departure_alert: { type: Boolean, default: false },
    adaptive_high_beam_assist: { type: Boolean, default: false },
    rear_cross_traffic_alert: { type: Boolean, default: false },
    rear_cross_traffic_collision_avoidance_assist: {
      type: Boolean,
      default: false,
    },
    blind_spot_monitor: { type: Boolean, default: false },
  },
  advanced_internet_feature: {
    live_location: { type: Boolean, default: false },
    over_the_air_updates: { type: Boolean, default: false },
    google_alexa_connectivity: { type: Boolean, default: false },
    inbuilt_apps: { type: Boolean, default: false },
    remote_immobiliser: { type: Boolean, default: false },
    digital_car_key: { type: Boolean, default: false },
    navigation_with_live_traffic: { type: Boolean, default: false },
    send_poi_to_vehicle_from_app: { type: Boolean, default: false },
    live_weather: { type: Boolean, default: false },
    e_call_and_i_call: { type: Boolean, default: false },
    sos_button: { type: Boolean, default: false },
    rsa: { type: Boolean, default: false },
    over_speeding_alert: { type: Boolean, default: false },
    tow_away_alert: { type: Boolean, default: false },
    smartwatch_app: { type: Boolean, default: false },
    valet_mode: { type: Boolean, default: false },
    emergency_assistance: { type: Boolean, default: false },
    geo_fence_alert: { type: Boolean, default: false },
  },
  registration_and_charges: {
    individual_registration: { type: SchemaTypes.String, default: 'N/A' },
    insurance: { type: SchemaTypes.String, default: 'N/A' },
    other_charges: { type: SchemaTypes.String, default: 'N/A' },
  },
  warranty_and_features: {
    manufacturer_warranty: { type: SchemaTypes.String, default: 'N/A' },
    battery_warranty_years: { type: SchemaTypes.String, default: 'N/A' },
    warranty_years: { type: SchemaTypes.String, default: 'N/A' },
  },
});

const dbModel = model('carvariants', schema);
const MONGO_URI = 'mongodb+srv://amantyagi2223:admin123@cluster0.k0xonxj.mongodb.net/prod_carservice'; // Replace with your MongoDB URI


async function loadData(data) {
    try {
      // Connect to MongoDB
      await connect(MONGO_URI);
      console.log('Connected to MongoDB');
  
      // Insert data into the database
      const result = await dbModel.insertMany(data);
      console.log(`${result.length} data have been successfully added.`);
    } catch (error) {
      console.error('Error loading data:', error);
    } finally {
      // Close the database connection
      await disconnect();
      console.log('Disconnected from MongoDB');
    }
  }
  
  module.exports = {loadData}